### ISSUE TITLE
Offer SASL capability again if user gets unidentified

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3-specifications#103]
I am not sure if the title says anything, but discussion started at https://github.com/atheme/atheme/pull/415#issuecomment-66869694 and there it was said that this is ircv3 thing.

I open this issue, because no one else seems to do it.

**Comment by kaniini** [comment]
Charybdis supports configuring the SASL agent now.

**Comment by kaniini** [comment]
Regarding LOGOUT, I recommend `DEAUTHENTICATE` as a message to log out of an account.

**Comment by kaniini** [comment]
charybdis has the core of `sasl-reauth` in place, but the numerics will need to be determined still

**Comment by attilamolnar** [comment]
> spec: CAP sasl-reauth
> [clients] just sends the same AUTHENTICATE <mech> and continues from there

Why do we need the cap? Clients could be allowed to simply re-send AUTHENTICATE. If the server or services have no support for it, the reauth will fail because of an error from the server or will fail due to timeout (which can occur naturally anyway when servers split due to ping timeout).

> ircd: notification about SASL agent availability

cap-notify handles this by sending CAP ADD or CAP DEL for the `sasl` cap, cap-notifiy is implicitly enabled by negotiating 3.2

> ircd: configuration of SASL agent's server name (to know when the agent is online)
> ircd: AUTHENTICATE when already registered
> clients: /auth command

Not relevant for this feature/spec to progress.

**Comment by grawity** [comment]
> Why do we need the cap? Clients could be allowed to simply re-send AUTHENTICATE. If the server or services have no support for it, the reauth will fail because of an error from the server or will fail due to timeout (which can occur naturally anyway when servers split due to ping timeout).

I'd guess for the same reasons sasl-3.1 requires the cap to send AUTHENTICATE at all; it's there primarily to inform the client...

**Comment by kaniini** [comment]
Yeah we decided cap-notify ought to do the trick instead.

**Comment by attilamolnar** [comment]
Keep in mind that cap-notify is not required to be in the CAP LS reply if the server is 3.2, we need to discuss whether a client needs to discover if a server is 3.2 and if yes, how should it do so.
