### ISSUE TITLE
capability negotiation: don't allow clients to request unsupported capabilities

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3-specifications#151]
Limnoria's behaviour is first to perform `CAP LS` and then request all capabilities that Limnoria supports including those which the server doesn't support.

Please see also the discussion at https://github.com/ProgVal/Limnoria/issues/1115.

**Comment by Aerdan** [comment]
Clients that request unsupported caps will have the request NAK'd already. If they don't, that's a server bug.

**Comment by Mikaela** [comment]
They do, but is there any use in spamming the server with requests for capabilities that it doesn't support while the client knows what is supported based on `CAP LS`?

**Comment by SaberUK** [comment]
Its valid behaviour to blindly request capabilities but I don't think we should encourage it. A well written client should `CAP LS` and then only request supported capabilities.

**Comment by Mikaela** [comment]
Shouldn't there be at least recommendation to not request capabilities that the server doesn't support? Limnoria, as seen on the linked issue, performs `CAP LS` and then requests capabilities which it supports ignoring `CAP LS`.

**Comment by DarthGandalf** [comment]
@Mikaela @ProgVal said it does not request `CAP LS`

**Comment by grawity** [comment]
@Mikaela Maybe there should, but OTOH the spec can't really cover all stupid things an implementer could do

**Comment by ProgVal** [comment]
Now it does. https://github.com/ProgVal/Limnoria/commit/e2b3b917e5227981979a0b7a65afb88b231eaffc

**Comment by kaniini** [comment]
I think this can be closed, there is no documentation issue here as far as I can see.

**Comment by Mikaela** [comment]
So stupid behaviour continues being OK.

**Comment by SaberUK** [comment]
@Mikaela It might be stupid behaviour but it is perfectly valid as per the CAP specification.

**Comment by grawity** [comment]
It's one of those behaviours that are hard to sensibly forbid, just like when some clients send a burst of `JOIN #foo` commands instead of having one `JOIN #foo,#bar,#baz,#qux`. (Or, like bot writers "parsing" the received messages with `if ($line =~ /PRIVMSG/)` instead of following the ABNF. Sigh.)

I mean, if the implementer didn't care to use `CAP LS` and wrote twice as much code to implement a REQ loop, then they're not going to be discouraged by a "MUST NOT" in the spec.

And enforcing it server-side would be just as stupid – it can't kill the connection just because the client did two REQs in a row :|

**Comment by Mikaela** [comment]
And the point of this issue was no make it invalid with theCAP specification, but I see no reason to continue this discussion.
