### ISSUE TITLE
An overview for humans

### ISSUE THREAD

**Issue by techtonik** [ircv3/ircv3-specifications#154]
The site is all about specifications. Is there a plan to make information for humans - why new protocol, what issues need to be addressed, what are those shiny `exciting, useful new features for networks, and client / server authors` that `stakeholders in the IRC protocol, such as IRC networks and IRC network operators` interested in?

**Comment by DanielOaks** [comment]
Just as an FYI, the site repo is [here](https://github.com/ircv3/ircv3.github.io), but this is a really important issue. It's definitely something important to look at, and https://github.com/ircv3/ircv3.github.io/issues/8 is tangentially related to that.

Though a general "why" page and/or a broad overview of the nice stuff IRCv3 gives networks and software authors could be useful. Could you repost this issue in the site repo, please?

**Comment by Mikaela** [comment]
I think https://github.com/ircv3/ircv3.github.io/issues/7 is also somewhat related as humen are likely to come from Google or other search engine and they will only see weird mess instead of snippet of what IRCv3 (or more importantly the specs that look the most horrible in those snippets) are about.

**Comment by techtonik** [comment]
Reposted to https://github.com/ircv3/ircv3.github.io/issues/9
