### ISSUE TITLE
SASL: Tell why exactly it fails

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3-specifications#157]
I am not sure if this is IRCv3 relevant or something that would be in specs, but anyway it would be a big help if SASL could tell what is wrong with it not identifying. Currently I think that is either

* wrong username
* wrong password
* unsupported mechanism

**Comment by attilamolnar** [comment]
Differentiating between wrong username or password is a bad idea security wise and should not be implemented. The mech list should be sent to the client in case it picks an unsupported mech, AFAIK.

**Comment by Mikaela** [comment]
```
2015-06-26 20:50:39+0300 < Mikaela> I think they should be separate so the person would know that they typed the username correctly and don't show password error if the username is wrong
2015-06-26 20:51:20+0300 < Mikaela> and the mechanism would also be helpful and if it could communicate supported mechanisms, but I think IRCv3.2 already does that.
2015-06-26 20:51:20+0300 < Mikaela> And I am not fully sure if that is something standard can say or is it implementation specific matter
2015-06-26 20:51:49+0300 < Aerdan> that is exactly why it needs to be the one, otherwise it leaks the user's existence
2015-06-26 20:52:37+0300 < Mikaela> but aren't there ratelimits and you could see the existence of user simply by connecting?
2015-06-26 20:57:54+0300 < grawity> what's the actual problem with "leaking the user's existence"
2015-06-26 20:58:06+0300 < grawity> it's silly
2015-06-26 20:58:09+0300 < grawity> usernames are not passwords
```

> The mech list should be sent to the client in case it picks an unsupported mech, AFAIK.

Most of clients I know let user to choose one mechanism and never try another.

**Comment by Mikaela** [comment]
> 2015-06-26 21:03:22+0300 < Aerdan> never mind, it's a moot point when registering also leaks.

**Comment by grawity** [comment]
For most cases it is useless paranoia. Like on many websites, when you get the generic "user/pass wrong" message, you can find out whether the username exists by trying to _register_ it.

It might improve security in some situations for some kinds of closed-down "fortress" systems, but IRC in general is really not comparable to that, it's more like forums or Twitter where the username is already shown everywhere.

And if someone really tries to build a fortress with Atheme and chewing gum, they'll likely be patching stuff out services & ircd anyway, so they can just patch out one extra message / status code.

---

That said, some mechanisms don't actually have such a distinction in the first place, since they look up accounts by the "password" (e.g. EXTERNAL does a lookup with provided certificate fingerprint).

**Comment by jwheare** [comment]
ERR_SASLFAIL already takes a message parameter. In general, the contents of the message is implementation specific, so it could easily be used to indicate the reason at the implementor's discretion. I see no reason not to document it as such.

**Comment by grawity** [comment]
Many IRC clients have to be modified anyway, as they discard the current message (as with many other numerics). So how about extending it? For a new-style error response, send _two_ parameters, an error code and a textual description. E.g. `authn-no-account`, `authn-account-locked`, `authn-bad-credentials`, `authz-denied`, etc. Clients could do something UI-specific or language-specific with that.

**Comment by kaniini** [comment]
@jwheare :+1: lets just close this stuff.

**Comment by attilamolnar** [comment]
@grawity I think in the long term password-based SASL auth should be replaced by a PAKE implemented in the TLS layer. That's light years ahead in terms of security compared to what we have now. For the short term the solution proposed by @jwheare may be used if desired. Therefore, I don't think we should spend time doing what you proposed.

**Comment by ChickenNuggers** [comment]
Should we mark this as closed?

**Comment by jwheare** [comment]
Closing as already covered by `ERR_SASLFAIL`
