### ISSUE TITLE
Suggestion: Send messages to users in the context of a specific channel (IRCX whisper)

### ISSUE THREAD

**Issue by puckipedia** [ircv3/ircv3-specifications#163]
Basically, this would add an intent, `@intent=whisper`, that indicates to the client that this message should be shown to the client in the buffer of a specific channel, like the IRCX WHISPER. Use cases for this would be: Game bots, welcoming messages, etc.

A few examples of how the intent might look like:
- `@intent=whisper;channel=#<channel> PRIVMSG puckipedia :Welcome to #<channel>!`
- `@intent=whisper:#<channel> PRIVMSG puckipedia :Welcome to #<channel>!`

Other discussion points: Should it be limited to ops/voiced, or would it follow +n, etc.

**Comment by kaniini** [comment]
it should be `@intent=redirect;target=[target]` in my opinion, so that the intent is more flexible.  this would allow send to server status window, for example.  some care might need to be taken to reject invalid targets (queries other than source/target, to avoid 3rd party injection), for example.

**Comment by TingPing** [comment]
This is also basically the same thing as sending a prefixed message to `@#channel` that only ops receive, so it should be flexible enough to handle that. (since that isn't standardized yet is it, or do we want it to be?)

**Comment by Aerdan** [comment]
I disagree with the target being a separate tag; it's data relevant to the intent, so it should be *part of* the intent. Aside from that, `@intent=redirect` sounds like a better choice.

**Comment by kaniini** [comment]
I do plan to document `WALLCHOPS` behaviour in harmony, however if we want to go this route instead I won't bother with that.

**Comment by kaniini** [comment]
@TingPing whisper (1 to 1) isn't really the same thing as wallchops (1 to N), but this intent could cover both usecases by clarifying that it's a wallchops message better :)

**Comment by DarthGandalf** [comment]
Why do you need this to be intent? Intents are replacement for CTCP, and this doesn't look right:
```
@redirect=#chan PRIVMSG foo :\x01REDIRECT bar\x01
```

**Comment by grawity** [comment]
@DarthGandalf: If intents are replacements for CTCP, that's just more of a reason _to_ use intents (or whatever), because if one wanted to implement whispers in the base tag-less protocol, they would very likely use CTCP for that.

So your example doesn't look right not because it's "incompatible", but because the example itself is based on nonsense. It's not what a CTCP-based implementation would look like. Remember that CTCPs are from a world without message tags. So a much more plausible implementation of WHISPER in base protocol would be very similar to the existing ACTION format:

    PRIVMSG Darth :\x01CHANWHISPER #ircv3 This looks right\x01

_(Disregarding the current ChanServ hack of "NOTICE Nick :[#chan] Text", which is even worse.)_

So if you can map ACTION to an "intent", you can map WHISPER to the same.

**Comment by Aerdan** [comment]
> Why do you need this to be intent? Intents are replacement for CTCP, and this doesn't look right:
>   `@redirect=#chan PRIVMSG foo :\x01REDIRECT bar\x01`

Intents are not a replacement for CTCP particularly, they are a replacement for a class of issues relating not just to CTCP but also to use of NOTICE, etc., which has a lot to do with #138.

**Comment by jwheare** [comment]
This can be achieved with 3.3 client-only tags now. Intents are dead as of #270

**Comment by jwheare** [comment]
See https://github.com/ircv3/ircv3-specifications/pull/498
