### ISSUE TITLE
Extended leave

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3-specifications#175]
*I have doubt that this is wrong place to report this, but I am not fully sure, if I should go to client instead, please tell me.*

I am liking extended-join a lot, but join and part/quit messages look quite mismatched now and I am wondering if NickServ account and real name could also be shown in part/quit messages.

*The reason why I am not fully sure if this should be something on IRCv3 side or client is that client with `account-notify` (which at least with WeeChat performs `who`-poll when joining on channel) `extended-join` has all information available for implementing this by itself. Of course that way it would appear in less clients.*

**Comment by SaberUK** [comment]
Its hard to implement it with PART because you can't add the real name to the PART without adding some kind of escaping system because unlike with JOIN, PART has a reason parameter which is <trailing>`.

Any decent client should be able to implement this without protocol extensions by tracking the extra information when the user joins and displaying it when the user quits.

:-1:

**Comment by Mikaela** [comment]
> Any decent client should be able to implement this without protocol extensions by tracking the extra information when the user joins and displaying it when the user quits.

So I thought so I will move to WeeChat's issue tracker.
