### ISSUE TITLE
Add a README pointing to the website as canonical

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#216]
There have been occasions in the past where people have taken the specs in the repo as is, without understanding the extra context provided by the website, e.g. the draft status of 3.3. This should be addressed with a README stating something like:

> This repository contains specifications that are still in draft stage, please refer to http://ircv3.net/irc/ for a structured listing of finalised specifications.

**Comment by jwheare** [comment]
For related bonus points, adding something like `status: draft|published` to the yaml front matter would provide an extra inline hint that a spec might not be finalised, and could even allow for more granular status warnings on the website, rather than the simple 3.3 = draft rule we have now. Might be useful as more 3.3 specs get closed to finalisation.

**Comment by DanielOaks** [comment]
I think adding the `status` or related to the YAML front-matter could be good. The website just assuming 3.3 == draft with big red warning was originally just because I didn't want to bother putting in a PR to change the actual specifications. Especially with some people actually looking at the repo documents it would make things more explicit.

Honestly, maybe even just something like `wip: true` since I think flags make more sense here. I can submit a change doing this for the repo, and then update the website to match.

Given it's basically just flags to show various extra messages with the specs, I can do something similar with https://github.com/ircv3/ircv3.github.io/issues/50 at the same time and something like

```yaml
deprecated: Please refer to the mechanisms specified on the [SASL Mechanisms](http://ircv3.net/docs/sasl-mechs.html) page, etc etc why it's deprecated
```

**Comment by attilamolnar** [comment]
Readme added, yaml front matter updated with WIP status indicator - @DanielOaks thanks for your work on this.
