### ISSUE TITLE
SASL numeric 904 aka ERR_SASLFAIL and invalid credentials (and other errors).

### ISSUE THREAD

**Issue by Robby-** [ircv3/ircv3-specifications#317]
Currently SASL has no dedicated numerics for telling the user or admin that an error is either due to invalid credentials or due to any other errors not explicitly mentioned by other numerics, it is thrown together in one numeric: 904. I think it would be better if there was a dedicated numeric for every other error and one for invalid credentials, as to reduce any possible confusion for the user and/or admin when troubleshooting possible issues.

I was thinking of re-purposing 904 to be *only* for failed authentication due to invalid credentials and creating another numeric for every other error not covered by an existing one.

**Comment by grawity** [comment]
If a new "final" numeric is used, I can see compatibility problems in both s2s and c2s protocols – new services won't be understood by old ircds (which expect D S or D F), and new ircds won't be understood by old clients (which expect 903 or 904).

So an "extended error information" numeric could certainly be defined, but it would still be used _together_ with the existing 904, rather than immediately indicating failure on its own.

We already have one such error case – using an unknown mechanism results in an additional 908 message (containing the mech list) before the final 904.

**Comment by jwheare** [comment]
@Robby- was there a specific error case you had in mind here that isn't covered by other errors?

**Comment by Robby-** [comment]
Not really, only the case I had typed in my opening post.

**Comment by jwheare** [comment]
I can’t see a specific case in the original post, which was why I asked :)

**Comment by jwheare** [comment]
Sure. We can reopen if a specific need for extended info arises.
