### ISSUE TITLE
Standardize channel services and make them part of IRCD

### ISSUE THREAD

**Issue by GIJack** [ircv3/ircv3-specifications#376]
I feel it should be the responsibility of the IRCd to handle nickserv/chanserv/operserv/etc... data, and I feel this should all be done in band via raw commands.

As opposed to some IRCds that do this today, data sent via raw commands, should be returned in a raw command S2C, in formatted data, and it should be up to the client to parse it.

/msg nickserv should retain legacy functionality sendding notice back. Every IRCd should cache a copy of access rules, and they should be enforced/synced/aliased with channel and server mode settings.

**Comment by DanielOaks** [comment]
Yep, this is something I want to tackle. #276 begins the work of exposing NickServ functionality to more native protocol methods so that clients can write interfaces on top of it. That particular spec only handles registration, but the way it's done is explicitly designed to allow future extensibility.

Once that PR is accepted, I'll be submitting basically the same thing but for channels. I'm not submitting it until the account management PR is accepted because keeping two separate PRs in-sync in terms of the API is weird and annoying. Once that PR is accepted, we'll know the interface that works and everyone agrees with to manage accounts extensively, and we can exactly the same interface to manage channels as well.

This should be filed into the https://github.com/ircv3/ircv3-ideas repo instead, as well, because there's stuff to work out with it.

**Comment by DanielOaks** [comment]
I'll close this and open an issue on the -ideas repo around this. This issue conflates standardising the channel services (a protocol concern) and making them part of the IRCd (an implementation concern which it doesn't make sense for us to mandate or worry about), so the other issue can be specific about this. Thanks for the issue though, contributions are always cool!
