### ISSUE TITLE
Can a server reply with several CAP LS in 302-less implementation ?

### ISSUE THREAD

**Issue by lel-amri** [ircv3/ircv3-specifications#405]
From my understanding of the spec, a server that doesn't supports 302 can reply with several CAP LS to a CAP LS request.

Let's say a client that does supports 302 sends CAP LS 302 to a server that doesn't supports CAP LS 302, and that the said server has so much capabilities that it needs to reply with two CAP LS. In this case, the exchange would be:

    Client: CAP LS 302
    Server: CAP * LS :cap1 cap2 cap3
    Server: CAP * LS :cap4 cap5

From my understanding of the spec, I can raise these statements:

1. A server isn't required to send multiline CAP LS replies
2. A client can't know whether the server does supports CAP LS 302 or doesn't
3. It is unspecified whether upon receiving CAP LS (non-302, and 302 altogether) the client should _replace_ or _make and addition to_ its set of known server's supported capabilities
4. A client isn't required to wait for several CAP LS replies

Given these statements, for a client making a CAP LS 302 request to a server that doesn't supports 302, all these behavior are valid:

1. The client gets `CAP * LS :cap1 cap2 cap3`, replaces its internal set so it becomes `(cap1, cap2, cap3)`, then drops `CAP * LS :cap4 cap5` because it appear to be unsolicited
2. The client gets `CAP * LS :cap1 cap2 cap3`, replaces its internal set so it becomes `(cap1, cap2, cap3)`, then upon receiving `CAP * LS :cap4 cap5` replaces its internal set so it becomes `(cap4, cap5)`
3. The client gets `CAP * LS :cap1 cap2 cap3`, updates (or initialize, if it's a fresh connection) its internal set so it becomes `(cap1, cap2, cap3)`, then upon receiving `CAP * LS :cap4 cap5` updates its internal set so it becomes `(cap1, cap2, cap3, cap4, cap5)`

Real-life situation problems can occurs for the behaviors 2 and 3: For example, an application that can adapt its behavior given what capabilities are offered by a server, and for which behaviors aren't all equal but have a preference order, a sub-optimal behavior could be enabled for behavior 2, and for behavior 3 in case the app doesn't wait a certain amount of time for several CAP LS replies (Still, even this "solution" poses a problem for the user (The app doesn't work until either it finished waiting for CAP LS replies, or it got a set which allows the most optimal behavior)). This is a problem only if the app choose to be a good citizen towards the server (Meaning: It won't send REQ for capabilities unsupported by the server (Otherwise it could blindly send REQ and try all sets in preference order until it finds one that is accepted by the server)).

302-less world isn't exempt of a similar issue: From my understanding of the spec, I can re-raise statements 2 and 3, thus the real-life situation problem cited above still applies.

In my opinion there is several ways to fix this:

* The one I like better is to specify that clients must drop unsolicited CAP replies (LS, ACK, NAK altogether) AND that clients must replace their internal set upon receiving solicited CAP LS replies AND that servers must send multiline CAP LS (if client asks with 302) in case they needs to reply with several CAP LS.
  This solution implies that servers with too much capabilities so they don't fit on a single reply couldn't advertise them all.
* To specify that clients must update their internal set upon receiving CAP LS (whether the are multiline or not).
  It poses a problem for the real-life situation problem I cited above. The clean way to handle it both ways (server and user) would be to take a decision upon receiving the first CAP LS reply, then redo the "behavior chosing" process (request to disable all capabilities, then request a new set to enable a newly most optimal behavior) each time a CAP LS reply is received. But in this case I don't see the point of multiline CAP LS to exists (It seems to be that multiline CAP LS solve the issue 302-less world have).
* To have a way for clients to know whether the server supports a certain version, so clients could know if several non-multiline CAP LS replies are to be expected.
  The problem I cited right above ("_The clean way to handle it both ways [...]_") applies here too, though.
* Probably a f*ckton of other solutions I can't think of.

**Comment by DanielOaks** [comment]
Based on discussions in the channel, this might be getting resolved in different ways, buuuuut I'll have a crack at this.

> Let's say a client that does supports 302 sends CAP LS 302 to a server that doesn't supports CAP LS 302, and that the said server has so much capabilities that it needs to reply with two CAP LS.
This case doesn't exist. If a server ever did get to that point, it'd most likely support 302 (afaik Oragono is the only one that's approached/passed the length limit and we've supported 302 forever).

Of the outlined client behaviours, the only sane one is 3. But, again, this almost certainly wouldn't ever be a real concern because any server that's going to be advertising that many capabilities is probably going to take the time to implement the 302 multiline stuff. The 'issue' of servers spreading cap advertisements across multiple lines and the client not knowing where it ends is a known problem. It's why the 302 multiline stuff exists. If a server messes up clients by getting into this situation then there's a known solution: server implements 302 multiline stuff.

We don't need to try and solve something that isn't an issue, and that we've already made a solution for. Clients should do their best but it's known that it's undefined behaviour – that's why the defined fix exists.

**Comment by lel-amri** [comment]
I made these assumptions regarding multiline CAP LS (Without knowing the origins of it):

1. multiline CAP LS allows a client to update its set only once the server finished sending its set
2. multiline CAP LS allows a client to know what is the complete set offered by the server

   Otherwise, we can't distinguish:
   
       (msg1) Server: CAP * LS :* cap1 cap2
       (msg2) Server: CAP * LS :cap3 cap4

   from:

       (msg3) Server: CAP * LS :cap1 cap2
       (msg4) Server: CAP * LS :cap3 cap4

   _msg4_ can either be:
   * an unsolicited message advertising a new set of capabilities (meanwhile, `cap1` and `cap2` got disabled server-side)
   * a required message because all server supported capabilitites didn't fit in _msg3_

> Of the outlined client behaviours, the only sane one is 3.

Your statement implies:
* That assumption 2 is wrong and so it implies that a client have no way to know whether a capability got disabled server-side (Assuming a server wouldn't implement `cap-notify` if it doesn't implement CAP LS 302).
* That two succeding multiline CAP LS are additive, and that the latter one doesn't replace the former one.

I have a problem with both implications, I feel like we could take advantage of this (unexpected ?) feature of multiline CAP LS. That's only my opinion, though.

**Comment by DanielOaks** [comment]
I think the (msg1) is wrong there, do you mean `Server: CAP * LS * :cap1 cap2`, where the `*` is a separate param? I'll assume so.

> That assumption 2 is wrong and so it implies that a client have no way to know whether a capability got disabled server-side (Assuming a server wouldn't implement `cap-notify` if it doesn't implement CAP LS 302).

A client has no way to know whether a capability got disabled server-side unless the server implemented `cap-notify`. This is a known issue, which is why `cap-notify` exists.

> That two succeeding multiline CAP LS are additive, and that the latter one doesn't replace the former one.

That's how I handle this case as a client, yes. But it's really explicit that this case is undefined behaviour. Clients can do any of the behaviours above, and that's known. That's why `cap-notify` and the `302` extensions exist, to fix this undefined behaviour. Because we **know** that it's undefined behaviour and have fixes for it, I don't see any real need to discuss it deeper. If a client finds a way to take advantage of this undefined behaviour or something like that, awesome. But on the IRCv3 side, we have already worried about this case as far as we're concerned.

**Comment by edk0** [comment]
paraphrasing my comment from IRC: the [original CAP implementation][ratbox-cap] and this [early draft spec][mitchell-draft] do the `*` thing. Somehow this was lost in the IRCv3 version of the spec. I think that can be considered an error, and the spec for pre-302 behaviour amended accordingly.

As for client behaviour in the presence of servers that don't do this—they should assume that successive `CAP LS` responses, assuming no intervening `CAP LS` request, add to the first;  unsolicited LS responses aren't a thing.

[ratbox-cap]: <http://svn.ratbox.org/svnroot/ircd-ratbox/branches/RATBOX_2_1/modules/m_cap.c>
[mitchell-draft]: https://tools.ietf.org/html/draft-mitchell-irc-capabilities-01

**Comment by lel-amri** [comment]
Now I can think of a way that allows a client to verify whether a server supports 302: Right after sending CAP LS 302, a client can ask CAP LIST and see whether `cap-notify` is enabled. Does it complies with the spec ?

@DanielOaks 

> A client has no way to know whether a capability got disabled server-side unless the server implemented `cap-notify`.

Then asking for CAP LS more than once holds little value. `cap-notify` would be the go-to choice to get updates on capabilities modifications. I understand why it's implicitly enabled, then.

> That's how I handle this case as a client, yes. But it's really explicit that this case is undefined behaviour. Clients can do any of the behaviours above, and that's known. That's why cap-notify and the 302 extensions exist, to fix this undefined behaviour.

I'm ok with this, although it doesn't solves the situation where a client supporting CAP LS 302 encounters a server that doesn't. Should we leave it to be undefined behavior as well ? (In my case I'd implement behavior 1 since unsolicited LS/ACK/NAK holds no value IMO. Plus, it hugely simplifies what applications can expect.)

@edk0 

> paraphrasing my comment from IRC: the [original CAP implementation](http://svn.ratbox.org/svnroot/ircd-ratbox/branches/RATBOX_2_1/modules/m_cap.c) and an [early draft spec](https://tools.ietf.org/html/draft-mitchell-irc-capabilities-01) do the `*` thing. Somehow this was lost in the IRCv3 version of the spec. I think that can be considered an error, and the spec for pre-302 behaviour amended accordingly.

I'd like that, even though I'm a neophyte with IRCv3.

> **As for client behaviour in the presence of servers that don't do this—they should assume that successive CAP LS responses**, assuming no intervening CAP LS request, **add to the first**; unsolicited LS responses aren't a thing.

I'm ok with this.

> As for client behaviour in the presence of servers that don't do this—they should assume that successive CAP LS responses, **assuming no intervening CAP LS reques**t, add to the first; unsolicited LS responses aren't a thing.

I don't see how a client can identify what CAP LS request a CAP LS reply is referring to.

**Comment by edk0** [comment]
> I don't see how a client can identify what CAP LS request a CAP LS reply is referring to.

It's easy if only one has been sent :)

**Comment by DanielOaks** [comment]
> Now I can think of a way that allows a client to verify whether a server supports 302: Right after sending CAP LS 302, a client can ask CAP LIST and see whether cap-notify is enabled. Does it complies with the spec ?

They could if they really wanted to. Still, clients don't need to and shouldn't worry about it.

> I'm ok with this, although it doesn't solves the situation where a client supporting CAP LS 302 encounters a server that doesn't. Should we leave it to be undefined behavior as well ?

Yep, this should be left as undefined behaviour.

**Comment by RyanSquared** [comment]
>> I'm ok with this, although it doesn't solves the situation where a client supporting CAP LS 302 encounters a server that doesn't. Should we leave it to be undefined behavior as well ?
>
> Yep, this should be left as undefined behaviour.

I believe this should be mentioned as undefined behavior in an updated version of the specification and be used as further purpose for encouraging implementations to move towards `CAP LS 302`.

**Comment by slingamn** [comment]
>Now I can think of a way that allows a client to verify whether a server supports 302: Right after sending CAP LS 302, a client can ask CAP LIST and see whether cap-notify is enabled. Does it complies with the spec ?

Belatedly, Oragono does not implement this, i.e., issuing `CAP LS 302` does not cause `cap-notify` to show up in the `CAP LIST` output. It's not clear to me that this is required by the specification (some discussion at https://github.com/oragono/oragono/issues/1093).

**Comment by edk0** [comment]
> > > I'm ok with this, although it doesn't solves the situation where a client supporting CAP LS 302 encounters a server that doesn't. Should we leave it to be undefined behavior as well ?
> > 
> > 
> > Yep, this should be left as undefined behaviour.
> 
> I believe this should be mentioned as undefined behavior in an updated version of the specification and be used as further purpose for encouraging implementations to move towards `CAP LS 302`.

Meh. The existing practice the spec *attempted* to capture already dealt with this case; the undefined behaviour and any associated problems follow directly from its omission. It's a specification error and should be corrected as such.

Leaving a spec broken in order to encourage people to move to a different spec seems pointless. People should use CAP 302 if they need it, not because mistakes have been deliberately left in CAP prime.

**Comment by jwheare** [comment]
If it was really a mistaken omission in the original ircv3 spec, I'd accept a PR to restore it, as long as clients that don't handle it aren't punished. Be good if anyone had insight on why it might have been omitted though.

**Comment by edk0** [comment]
FWIW for solanum we since looked at some clients and concluded that (a) the omission is now load-bearing, with things like ChatZilla failing to parse the lines with a `*`, and (b) some versions of Irssi (whose CAP parsing was implemented after the original implementation rather than the spec, I guess) just assume a line without a continuation `*` is the last one even though they didn't send CAP 302. There doesn't seem to be a safe way to communicate multiple lines of CAP to both groups of clients, so we just added a priority flag to make sure established caps (list arrived at entirely arbitrarily) end up in the first line, which is the only one we'll send to pre-302 clients.

**Comment by jwheare** [comment]
So what's the way forward? Just move the multiline stuff in the spec to not rely on 302 and accept that ChatZilla (and likely others) should be updated? Is an errata saying something like this enough? "multiline continuations in LS and LIST replies were unintentionally omitted from 301, software may need to be updated to support this format"

**Comment by edk0** [comment]
I'm not sure tbh. I think the safest option (which does make me a bit sad) is to just not send multiple lines of CAP to 301 clients, which in practice servers will have to do forever since we can't tell if a client is updated, make sure existing caps get to be in the one line, and make new ones depend on CAP 302. I'd like to correct the mistake but, solidly meh though it is, it should probably come with a best practice recommendation for servers that you can't send multiple lines of CAP LS 301 without confusing *some* clients.

**Comment by jwheare** [comment]
As it stands, the spec effectively already says that. Multiple lines are restricted to 302. As unfortunate as it is, if this can't be corrected safely, not sure what needs to be amended.

**Comment by edk0** [comment]
The spec currently says do send multiple lines, just don't include the `*`. That will definitely break some things, and it's hard to see how a hypothetical client *could* handle it correctly: suppose `sasl` is on the second line and you've already sent `CAP END` because you didn't know it was coming? So I don't really have a strong opinion about trying to "fix" the omission, but I'd like the spec's recommendation for 301 to be safer. Something like: clients SHOULD accept the multiline `*` syntax regardless of CAP version requested, servers SHOULD NOT send more than one line of CAP LS/LIST response for 301.

**Comment by jwheare** [comment]
How about this:

> Servers MAY send multiple lines in response to `CAP LS` and `CAP LIST` but SHOULD NOT send them to clients that do not support CAP version `302`. Clients that support CAP version `302` MUST and other clients SHOULD handle the continuation format described as follows:

**Comment by edk0** [comment]
sgtm

**Comment by jwheare** [comment]
PRed #429

**Comment by jwheare** [comment]
@lel-amri does the PR address all concerns raised in this issue? If not, can you recap in a clear summary anything else that needs clarifying?

**Comment by lel-amri** [comment]
A short summary on the opinions expressed about this issue:

* @DanielOaks and @RyanSquared believe the spec should be left as it

* @edk0 pointed out that the original draft-mitchell specification made the star-notation for multiline CAP LS replies mandatory

* @edk0 believe the spec should be amended with the following:

  * _pre-302 clients SHOULD handle multiline CAP LS replies_

  * _servers SHOULD NOT send multiline CAP LS replies to pre-302 clients_

From what has been said on this thread, here is the state of the art:

* Some versions of the _irssi_ client do handle the star-notation regardless of the 302 version

* The _solanum_ server handle this issue by only sending one CAP LS line to clients not advertising 302 support

----

I'm ok with @edk0's suggestion.

**Comment by jwheare** [comment]
Right, it just seemed like your original issue had a lot more going on. AFAICT all those points relate to the single issue addressed by the PR.

**Comment by lel-amri** [comment]
> Right, it just seemed like your original issue had a lot more going on. AFAICT all those points relate to the single issue addressed by the PR.

Indeed. @edk0's suggestion is making the "good citizen behavior" clearer, potentially narrowing the undefined behavior extent. Following the fix, my client implementation will only consider "solicited" CAP LS/LIST replies. It implies that the first non-star-prefixed CAP LS/LIST reply will be considered as the end of a set of capabilities and that subsequent CAP LS/LIST replies will be dropped until a new CAP LS request is sent.

**Comment by jwheare** [comment]
All I'm asking is can I close this issue in place of the PR?

**Comment by lel-amri** [comment]
Yes
