### ISSUE TITLE
Standardize pre-welcome FAIL ACCOUNT_REQUIRED

### ISSUE THREAD

**Issue by emersion** [ircv3/ircv3-specifications#479]
It seems like some ergo servers will send the following when performing connection registration without logging in:

    FAIL * ACCOUNT_REQUIRED :You must log in with SASL to join this server
    ERROR :You must log in with SASL to join this server

It would be nice to standardize this error code so that clients can reliably match it. It's not in the registry atm.

Ref https://github.com/ergochat/ergo/blob/c9b54ee2b801909cc3944bedbd04bc4079c54d8a/irc/server.go#L305

cc @slingamn

**Comment by jwheare** [comment]
This should probably be added to the account-registration spec.

**Comment by slingamn** [comment]
It's not inherently tied to that spec, though; it applies to situations where the problem can't be corrected by registering an account (i.e. private servers with closed registration). We've been sending it since well before that spec was proposed.

I would submit a PR to add this to https://ircv3.net/registry#fail-codes as long as no one objects to the use of `*`.

**Comment by jwheare** [comment]
I'm not sure it matters tbh, it's a convenient and clearly related place to document it in an actual spec, rather than a dangling registry entry.
