### ISSUE TITLE
Monitor spec doesn't state why WATCH is "severely flawed"

### ISSUE THREAD

**Issue by attilamolnar** [ircv3/ircv3-specifications#49]
A lot of people asked what is the difference between WATCH and MONITOR, I think a reasoning should be added to the document.

**Comment by kaniini** [comment]
@syzop the main difference between MONITOR and WATCH is that it uses ISON-style notifications instead of a separate numeric per client. this is intended to be more bandwidth efficient than WATCH's behaviour.

WATCH being deprecated by IRCv3 does not mean that it is 'going bye-bye', just that we would not advise it be implemented in new codebases.

**Comment by attilamolnar** [comment]
@syzop FYI ircd-ratbox has removed MONITOR support recently, does/will unreal 3.4 implement it? If not, then as far as I know only charybdis will support it in the short term.

    r28669 | androsyn | 2015-09-29 11:04:13 -0400 (Tue, 29 Sep 2015) | 1 line
    remove monitor, nobody really uses it, rebuild automake to reflect its removal as well

http://svn.ratbox.org/svnroot/ircd-ratbox/trunk/

**Comment by syzop** [comment]
@attilamolnar Thanks for letting me know. In UnrealIRCd (also in the upcoming 3.4 version) we have no support for MONITOR. We also have no plans to add it as we already have WATCH and see very little benefit in MONITOR.

**Comment by kaniini** [comment]
for what it's worth, ratbox has put MONITOR back.
