### ISSUE TITLE
Remove non-participants from list of participants

### ISSUE THREAD

**Issue by DarthGandalf** [ircv3/ircv3-specifications#84]
Only projects who participate in IRCv3 should be listed on website. It's better not to confuse people.

**Comment by Mikaela** [comment]
Which of those are actually participiants? Those that I know that I know and I am sure on being participiants are

* Atheme
* freenode (which I questiion, because of their old IRCd / https://github.com/freenode/ircd-seven/issues/1)
* InspIRCd (developers are on channel and it has modules)
* ZNC (one of the most active it appears).

**Comment by SaberUK** [comment]
@Mikaela Possibly useful: https://docs.google.com/spreadsheets/d/1lIhsF3zgCRQpvPtJmujVp5RfZqVL6OEg3fIlnwCrhjM/edit#gid=0

**Comment by kaniini** [comment]
The list of participants should probably just be replaced with that gdocs spreadsheet link.  There's not any real value in it anymore.

**Comment by attilamolnar** [comment]
@DarthGandalf Is this still an issue? http://ircv3.net/participation.html
