### ISSUE TITLE
Site and spec revamp before 3.2

### ISSUE THREAD

**Issue by attilamolnar** [ircv3/ircv3-specifications#89]
A few things that imho must be done before 3.2 and isn't specific to any extension:
- Add the .md extension to all markdown files.
- Format all specifications (old and new) to look saner.
- Add examples to all extensions that don't have one.

Implementing the enhancements in #44 would be good too, but I'm not aware of anyone working on those, so I propose we do this minimal treatment for now.

**Comment by kaniini** [comment]
I will handle this as soon as `sasl-reauth` is finished (#103).

**Comment by DanielOaks** [comment]
Alright, so for the spec documents to play nicely with Jekyll (Github pages generator), we'll also need to have some standard YAML front-matter on them, if we just want the website to use `git submodule` to pull this whole repo in as a submodule (which is the easiest way in terms of keeping specs on the website up-to-date).
 
An example of the required front matter would be something like this:
```yaml
---
title: IRCv3.2 Metadata
layout: spec
---
```
 
Purely as an example, this repo being submodule'd in the ircv3.github.io repo as `spec` would produce URLs like:
* `ircv3.org/spec/extensions/account-tag-3.2.html`
* `ircv3.org/spec/specification/metadata-3.2.html`
 
Which is a bit ugly due to the `spec/specification`, but I'm not sure what else we could name the submodule while still being sorta sane in URLs (maybe `git`?). Otherwise, could maybe rename the `specification` folder in this repo to `base`.
